name: Issue Report
description: File an issue
body:
  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of issue
      description: What type of issue? Select all that apply.
      options:
        - label: Anomaly report (something appears to not work correctly)
        - label: Enhancement request (describe the enhancement being requested)
        - label: Other (please ensure the description clarifies why the issue doesn't fall into either of the above categories)
  - type: textarea
    id: issue-description
    attributes:
      label: Descriptive summary
      description: Provide a detailed description of the problem or suggested new functionality. Be sure to include contextual info, as readers may not be aware of what you are doing.
  - type: input
    id: carma-version
    attributes:
      label: CARMA version where this issue was discovered
      description: What version are you running that you noticed this problem or deficiency? If this is an enhancement request, record the latest available version.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe is supposed to happen in the version noted above.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what happens in the version noted above that you'd like to change.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce the actual behavior
      value: |
        1. Do this
        2. Then do this
        3. ...
  - type: textarea
    id: related-work
    attributes:
      label: Related work
      description: Links to related tickets or prior related work here. If this is an enhancement request, this field may not apply.
